### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by DanielRuf** [paragonie/sodium-plus#14]
GHA is very interesting and I would provide a PR to migrate to it.

Did you already signup to the GHA beta? =)

**Comment by paragonie-scott** [comment]
I signed up but haven't received any emails from Github regarding it. I guess this is in limbo for the time being.

**Comment by paragonie-scott** [comment]
Oh, I just got the **Welcome to GitHub Actions!** email. Neat.

**Comment by DanielRuf** [comment]
Cool =) I'll provide a PR for this =)
