### ISSUE TITLE
Browserify and Minify

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/sodium-plus#21]
We should aim for `v0.4.0` to work in a web browser with a simple `<script />` tag, and allow our `v0.4.0` release to be shipped on CDNs.

**Comment by paragonie-scott** [comment]
#24

**Comment by paragonie-scott** [comment]
Done!

**Comment by dearsina** [comment]
Which CDNs support sodium-plus? I have yet to find a public one. Thanks.
