### ISSUE TITLE
hex to buffer?

### ISSUE THREAD

**Issue by lesDevGit** [paragonie/sodium-plus#30]
We looked through the docs but could not find how to turn a hex string into a buffer using the Utils, so we are using this function to return a Uint8Array (and use it as buffer):

```
function hexToBuffer(hexString) {
   return new Uint8Array(hexString.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));
}
```

...but `crypto_secretbox_open` rejects the ciphertext ("Ciphertext must be a buffer of at least 16 bytes") and nonce ("Nonce must be a buffer of exactly 24 bytes") created this way. They are 16< and =24 bytes, but they are not buffers according to sodium-plus (that is why the thrown SodiumError).

What would be the appropriate way to convert hex to buffer?

**EDIT:**
We also tried `return Buffer.from(hexString)` but it throws a **ReferenceError: Buffer is not defined**.

**Comment by paragonie-scott** [comment]
Yeah, `Buffer` support in browsers isn't great.

**Comment by lesDevGit** [comment]
Having a look at dist/sodium-plus.js `crypto_secretbox_open` function (line 2623 – 2639) we found that – as a quick solution – we could just add

```
ciphertext = (!Buffer.isBuffer(ciphertext)) ? Buffer.from(ciphertext) : ciphertext;
nonce = (!Buffer.isBuffer(nonce)) ? Buffer.from(nonce) : nonce;
```

after `await this.ensureLoaded();` (line 2624), so it turns the `Uint8Array` into a `Buffer`.

**Comment by paragonie-scott** [comment]
Please don't edit the dist files, as those are generated via browserify with each release and your changes will be rolled back.

I'll be making a congruent change in `v0.6.0`.

**Comment by paragonie-scott** [comment]
Can you give the `dist/` scripts that just landed in the `master` branch a whirl?

https://github.com/paragonie/sodium-plus/commit/3c0fd275a8ff5ab3559ed0dde636d59fe63ea9ff

**Comment by lesDevGit** [comment]
> Please don't edit the dist files, as those are generated via browserify with each release and your changes will be rolled back.
> 
> I'll be making a congruent change in `v0.6.0`.

We are aware that it is "bad practice" to edit the core files of any software (and normally we would not have done it), but we needed a solution ASAP – this is why we decided to settle with the one mentioned above until the new version is out.

**Comment by lesDevGit** [comment]
> Can you give the `dist/` scripts that just landed in the `master` branch a whirl?
> 
> [3c0fd27](https://github.com/paragonie/sodium-plus/commit/3c0fd275a8ff5ab3559ed0dde636d59fe63ea9ff)

thanks, will try and reply asap!

**Comment by lesDevGit** [comment]
works as intended, thank you !
