### ISSUE TITLE
sodium-native 3.0.0

### ISSUE THREAD

**Issue by davedoesdev** [paragonie/sodium-plus#33]
sodium-plus has 

```json
  "peerDependencies": {
    "sodium-native": "^2.4.6"
  },
```

Latest sodium-native is 3.0.0 so I get this warning:

```
npm WARN sodium-plus@0.6.0 requires a peer of sodium-native@^2.4.6 but none is installed. You must install peer dependencies yourself.
```

even though sodium-native is installed.

**Comment by paragonie-security** [comment]
They raised the major version. There were some BC breaks. #35 fixed this, so a new version will be released soon.

**Comment by paragonie-security** [comment]
`v0.7.0` is out.

**Comment by davedoesdev** [comment]
Thanks
