### ISSUE TITLE
Generate nonces within calls

### ISSUE THREAD

**Issue by davedoesdev** [paragonie/sodium-plus#34]
I was wondering whether sodium-plus could remove nonce as an argument to calls generate the nonces within the library.
This would prevent apps mistakenly re-using the same nonce.
The nonce would be returned along with the result, so the API would need changing.

**Comment by paragonie-security** [comment]
A higher-level library that depends on sodium-plus can easily do this. One such example is [ciphersweet-js](https://github.com/paragonie/ciphersweet-js).
