### ISSUE TITLE
Publish dist folder

### ISSUE THREAD

**Issue by jseparovic1** [paragonie/sodium-plus#36]
Hi,

Is it intentional that `dist` folder is missing from `files` key in `package.json` or in other words it is not published with the package?

I don't want to copy `dist` file to my project or use a cdn but would prefer to include it from `node_modules` since this is making it easier to maintain and all packages in a project are required in described way.

**Comment by Rikezenho** [comment]
+1

We are having trouble because of this in a project focused on front-end (browsers), because our webpack excludes node_modules files from Babel transpiling. When we try to minify, we get an error of "unexpected keyword <<const>>", because UglifyJs doesn't supports ES6 statements.

**Comment by paragonie-security** [comment]
Fixed in `v0.8.0`
