### ISSUE TITLE
Buffer() and new Buffer() are deprecated, showing warnings

### ISSUE THREAD

**Issue by furiousOyster** [paragonie/sodium-plus#40]
Thank you for this very helpful library.

As per https://nodejs.org/fr/docs/guides/buffer-constructor-deprecation/ these methods, used extensively throughout the codebase, are deprecated, and throw warnings.

Also as an unrelated side note, I see "let variable = 'something'" being used throughout as well where the variable is never reassigned - any reason you're not using 'const' ?

**Comment by paragonie-security** [comment]
This should be fixed in `v0.9.0`

**Comment by furiousOyster** [comment]
confirmed fixed
